            - name: PHP Insights
  # You may pin to the exact commit or the version.
  # uses: Novusvetus/action-phpinsights@87de2da8f041d4bb20231243fba2c44a80e69a6e
  uses: Novusvetus/action-phpinsights@1.1.16
  with:
    # Files to check
    files: # optional, default is **.php
    # Scan all files and not only changed
    scan_all: # optional
    # Path to PHP Insights executable
    phpinsights_path: # optional, default is php ~/.composer/vendor/bin/phpinsights
    # Min quality needed.
    min_quality: # optional, default is 90
    # Min complexity needed.
    min_complexity: # optional, default is 90
    # Min architecture needed.
    min_architecture: # optional, default is 90
    # Min style needed.
    min_style: # optional, default is 90
          
